name: Publish Package Workflow
description: Publish Package to JFrog Artifactory

inputs:
  tag:
    default: ""
    type: string
  python-version:
    default: "3.10"
    type: string
  token:
    required: true
    type: string
  user:
    default: "cai-eng"  # change default to your user
    type: string
  repo:
    default: "pypi-mlab"
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.python-version}}

    - name: Install poetry
      shell: bash
      run: pip install poetry

    - name: Artifactory credentials
      shell: bash
      run: |
        poetry config repositories.artifactory https://artifactory.astrazeneca.com/artifactory/api/pypi/${{ inputs.repo }}
        poetry config http-basic.artifactory ${{ inputs.user }}@astrazeneca.com ${{ inputs.token }}

    - name: Build package
      shell: bash
      run: |
        poetry version $(poetry version -s)${{ inputs.tag }}
        poetry build

    - name: Publish to Artifactory
      shell: bash
      run: |
        poetry publish \
          --repository artifactory \
          --username ${{ inputs.user }}@astrazeneca.com \
          --password ${{ inputs.token }}
