[tool.poetry]
name = "your-component"
version = "0.1.0"
description = "Kubeflow component for your-component."
authors = ["CAI Engineering"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Indepedent",
    "Topic :: Utilities"
]
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
# This version must also be changed in the ruff config.
python = "3.10"

[[tool.poetry.source]]
name = "colin"
url = "https://artifactory.astrazeneca.com/artifactory/api/pypi/colin-pypi/simple"
priority = "explicit"

[[tool.poetry.source]]
name = "mlab"
url = "https://artifactory.astrazeneca.com/artifactory/api/pypi/pypi-mlab/simple"
priority = "supplemental"

[[tool.poetry.source]]
name = "az-artifactory"
url = "https://artifactory.astrazeneca.com/artifactory/api/pypi/pypi-virtual/simple"
priority = "supplemental"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
